---

image_version: 4.5.2

image: "linuxserver/qbittorrent:{{ image_version }}"

downloads_dir: "/downloads"

config_dir: "/opt/torrent_client/config"
config_file: "/opt/torrent_client/config/qBittorrent.conf"
torrent_dir: "{{ downloads_dir }}/torrents"
process_dir: "{{ downloads_dir }}/process"
complete_dir: "{{ downloads_dir }}/complete"

torrent_client_domain: "torrent.{{ host_domain }}"
