---

- name: "State: Directories created"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "1000"
    group: "1000"
    mode: "0775"
  with_items:
    - "{{ config_dir }}"
    - "{{ torrent_dir }}"
    - "{{ process_dir }}"
    - "{{ complete_dir }}"
  become: true

- name: "State: Config file created"
  ansible.builtin.template:
    src: "qBittorrent.conf.j2"
    dest: "{{ config_dir }}/qBittorrent.conf"
    owner: "1000"
    group: "1000"
    mode: "0644"
  become: true

- name: "State: Container started"
  community.docker.docker_container:
    name: "torrent"
    image: "{{ image }}"
    pull: true
    state: started
    restart: true
    restart_policy: always
    volumes:
      - "{{ config_file }}:/config/qBittorrent/qBittorrent.conf"
      - "{{ torrent_dir }}:/torrents"
      - "{{ process_dir }}:/process"
      - "{{ complete_dir }}:/downloads"
    env:
      PUID: "1000"
      PGID: "1000"
      WEBUI_PORT: "80"
    ports:
      - 6881:6881
      - 6881:6881/udp
    labels:
      traefik.enable: "true"
      traefik.http.routers.torrent.rule: Host(`{{ torrent_client_domain }}`)
      traefik.http.routers.torrent.entrypoints: "websecure"
      traefik.http.routers.torrent.tls: "true"
      traefik.http.routers.torrent.tls.certresolver: letsEncryptResolver
      traefik.http.routers.torrent.service: torrent@docker
      traefik.http.services.torrent.loadbalancer.server.port: "80"
