---

- name: App directories created
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: "1000"
    group: "1000"
  with_items:
    - "{{ app_dir }}"
    - "{{ data_dir }}"
  become: true

- name: Plex container started
  community.docker.docker_container:
    image: "{{ plex_image }}"
    pull: true
    name: plex
    restart_policy: unless-stopped
    detach: true
    restart: true
    network_mode: host
    expose:
      - "{{ plex_exposed_port }}"
    mounts:
      - type: bind
        source: "{{ plex_media_directory }}/films"
        target: /films
      - type: bind
        source: "{{ plex_media_directory }}/serials"
        target: /serials
      - type: bind
        source: "{{ plex_media_directory }}/video"
        target: /video
      - type: bind
        source: "{{ data_dir }}"
        target: /config
    env:
      VERSION: docker
      PUID: "1000"
      PGID: "1000"
